name: Deploy Website

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Install less-watch-compiler
        run: npm install less-watch-compiler

      - name: Compile Less to CSS
        run: less-watch-compiler src/less src/css --run-once

      - name: Deploy
        run: npm run deploy
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}